### ISSUE TITLE
Broken Website Links (+ contact info)

### ISSUE THREAD

**Issue by naterarmstrong** [oreparaz/chaum#3]
Hey @oreparaz,

I was reading your great article, and noticed that most of the asset links are dead. I figured I'd give you a heads up.

Link: https://www.reparaz.net/oscar/misc/cmov

I tried to find other contact info, but the provided ones are dead, and I didn't want to pay linkedin to send a message, so just putting up an issue on your most recent (small) repo seemed like the best way.

**Comment by oreparaz** [comment]
Thanks for reporting. Unfortunately, it looks like the files in the asset links are gone. Gone for good. Data is lost.

If you're curious, there are some “backups” off-site that might be helpful:

   https://twitter.com/isislovecruft/status/1159548955920748546

Hope this helps.
